-- - name: Update system 
  apt: 
    update_cache: yes 
 - name: Install Python3 & pip 
  apt: 
    name: 
      - python3 
      - python3-pip 
    state: present 
 - name: Install Flask 
  pip: 
    name: flask 
 - name: Copy Flask app to server 
  copy: 
    src: app.py 
    dest: /opt/flask-app/app.py 
    owner: ubuntu 
    mode: '755' 
 - name: Create systemd service 
  template: 
    src: flask.service.j2 
    dest: /etc/systemd/system/flask-app.service 
 
- name: Reload systemd 
systemd: 
daemon_reload: yes - name: Enable and start Flask service 
systemd: 
name: flask-app 
enabled: yes 
state: restarted 
